landpage/urls.py
from django.urls import path
from .views import landpage

app_name = "land"

urlpatterns = [
    path("", landpage, name="landpage"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landpage.urls")), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landpage/models.py
from django.db import models

class LandModel(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    whatsapp = models.CharField(max_length=16, blank=False, null=False)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return self.name
    

landpage/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import LandModel
from .form import LandForm


def landpage(request):
    if request.method == "GET":
        form = LandForm()

        context = {
            "form":form
        }

        return render(request, "landpage/index.html", context)
    
    elif request.method == "POST":
        form = LandForm(request.POST)

        if form.is_valid():
            form.save()

            return render(request, "landpage/index.html", {"sucesso": True, 'form': form})
        else:
            return render(request, 'landpage/index.html', {'form': form})
        

templates/landpage/index.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2effe Sport</title>
    {% comment %} Css {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'landpage/css/base.css' %}">
    {% comment %} favicon {% endcomment %}
    <link rel="shortcut icon" href="{% static 'landpage/favicon.ico' %}" type="image/x-icon">
    {% comment %} Font awesome {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
    {% comment %} Animations {% endcomment %}
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    {% comment %} JQuery {% endcomment %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body>

    <section id="hero" class="section-p1">

        <img src="{% static 'landpage/img/logo.png' %}" alt="">
        <div data-aos="zoom-in">
            <h1><strong>Encontre seu uniforme</strong> <span class="text-alt-1">ideal</span> conosco!</h1>
        </div>
        <p>Clientes <i>satisfeitos</i> e que confiam na 2Effe Sport</p>

    </section>

    <section id="information" class="section-p1">

        <img src="{% static 'landpage/img/p1.png' %}" alt="">

        <div class="text-right" data-aos="zoom-in">
            <p>Na <strong>2effe Sport</strong>, transformamos sua paixão pelo esporte em vitórias memoráveis. Nossos uniformes não são apenas roupas são manifestações de excelência e orgulho. Com design meticuloso e materiais de alta qualidade, estamos aqui para elevar sua equipe ao próximo nível. Junte-se a nós e descubra como podemos tornar sua jornada esportiva ainda mais extraordinária.</p> 
        </div>
        
    </section>
    
    <section id="product-card" class="section-p1">

        <div class="text" data-aos="zoom-in">
            <h2>Alguns dos nossos Estilos</h2>
        </div>

        <div class="item">
            <div class="slide">
                <input type="radio" name="slide" id="c1" checked>
                <label for="c1" class="card">
                    <div class="row">
                        <div class="icon">1</div>
                    </div>
                </label>
            </div>
            <div class="slide">
                <input type="radio" name="slide" id="c2">
                <label for="c2" class="card">
                    <div class="row">
                        <div class="icon">2</div>
                    </div>
                </label>
            </div>
            <div class="slide">
                <input type="radio" name="slide" id="c3">
                <label for="c3" class="card">
                    <div class="row">
                        <div class="icon">3</div>
                    </div>
                </label>
            </div>
            <div class="slide">
                <input type="radio" name="slide" id="c4">
                <label for="c4" class="card">
                    <div class="row">
                        <div class="icon">4</div>
                    </div>
                </label>
            </div>
            <div class="slide">
                <input type="radio" name="slide" id="c5">
                <label for="c5" class="card">
                    <div class="row">
                        <div class="icon">5</div>
                    </div>
                </label>
            </div>
        </div>

    </section>

    <section id="text-box" class="section-p1">
        <div class="box" data-aos="flip-left">
            <h2>Por que escolher a 2effe?</h2>
            <p>Na 2effe, não apenas fabricamos roupas, criamos qualidade em cada detalhe. Com anos de experiência no setor, oferecemos o que há de melhor em tecnologia, design e sustentabilidade. Nossas peças são cuidadosamente confeccionadas com tecidos de alta durabilidade, garantindo conforto e estilo em cada coleção.</p>
        </div>
        <div class="box" data-aos="flip-right">
            <h2>faça parte da nossa historia</h2>
            <p>Na 2effe, cada peça conta uma história. A nossa começou com um sonho: transformar o mercado da moda com qualidade, inovação e responsabilidade. Ao longo dos anos, crescemos, evoluímos e continuamos a escrever novos capítulos ao lado de pessoas como você.</p>
        </div>
    </section>

    <section id="text-single" class="section-p1">

        <div class="text" data-aos="zoom-in">
            <h2>Quem somos nós</h2>
            <p>Somos a 2effe, uma confecção de roupas que nasceu da paixão pela moda e da vontade de oferecer produtos que combinam qualidade, inovação e responsabilidade. Atuamos no mercado há anos, sempre buscando transformar ideias em peças que unem estilo e conforto.</p>
        </div>

        <img src="{% static "landpage/img/background1.jpg" %}"></img>

        <div class="img"><img src="{% static 'landpage/img/p2.png' %}" alt=""></div>

    </section>

    <section id="promo-info" class="section-p1">

            <div class="container">
                <img src="{% static 'landpage/img/p3.png' %}" alt="">

                <div class="container-box">
                    <div class="text-box" data-aos="zoom-in">
                        <h4>promo</h4>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum doloribus vero nisi delectus natus adipisci officiis, dolores autem, sit cupiditate labor</p>
                    </div>
                    <div class="text-box" data-aos="zoom-in">
                        <h4>promo</h4>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum doloribus vero nisi delectus natus adipisci officiis, dolores autem, sit cupiditate labor</p>
                    </div>
                    <div class="text-box" data-aos="zoom-in">
                        <h4>promo</h4>
                        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eum doloribus vero nisi delectus natus adipisci officiis, dolores autem, sit cupiditate labor</p>
                    </div>
                </div>
            </div>

    </section>

    <section id="simulador">
        <div class="container" data-aos="zoom-in">
            <h2>Visite também nosso simulador e monte seu uniforme de forma pratica e rapida</h2>
            <a href="https://www.2effesportdf.com.br/simulador/">Ir para o simulador</a>
        </div>
    </section>

    <section id="newletter" class="section-p1">

        <div class="text" data-aos="zoom-in">
            <h2>Nós entramos em contato</h2>
            {% if sucesso %}
                <p class="sucess-menssage">Formulário enviado com sucesso!</p>
            {% endif %}
        </div>

        <div class="part">
            <div class="form">
                <form action="{% url "land:landpage" %}" method="post">
                    {% csrf_token %}
                    <label for="name">Nome</label>
                    {{ form.name }}
                    {% if form.errors.name %}
                        {{ form.errors.name }}
                    {% endif %}
                    <label for="whatsapp">whatsapp</label>
                    {{ form.whatsapp }}
                    {% if form.errors.whatsapp %}
                        {{ form.errors.whatsapp }}
                    {% endif %}
                    <label for="email">Email</label>
                    {{ form.email }}
                    {% if form.errors.email %}
                        {{ form.errors.email }}
                    {% endif %}
                    <button type="submit">Enviar</button>
                </form>
            </div>
            <img src="{% static 'landpage/img/p4.png' %}" alt="">
        </div>
        
    </section>

    <footer>
        <div class="col">
            <img src="{% static 'landpage/img/logo.png' %}" alt="">

            <h4>Contato</h4>
            <p><strong>Endereço:</strong> address</p>
            <p><strong>Telefone:</strong> (11) 91001 - 1001</p>
            <p><strong>Aberto:</strong> 10:00 - 19:00, Seg - Sab</p>

            <div class="follow">
                <h4>Redes Sociais</h4>
                <div class="icon">
                    <i class="fa-brands fa-instagram"></i>
                    <i class="fa-brands fa-twitter"></i>
                    <i class="fa-brands fa-pinterest"></i>
                </div>
            </div>       
        </div>
        
        <div class="copyright">
            <p>© 2024, ThZt - Html CSS Ecommerce Template</p>
        </div>

    </footer>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

    <script>
        AOS.init({
            offset: 200,  // ajusta o offset
            duration: 600, // duração das animações
            easing: 'ease-in-out', // tipo de animação
            once: true, // animação ocorre apenas uma vez
            mirror: false // animação não ocorre ao fazer scroll para cima
        });

        let currentIndex = 0;
        const slides = document.querySelectorAll('.slide input');
        const totalSlides = slides.length;

        function showNextSlide() {
            slides[currentIndex].checked = false; // Desmarcar o slide atual
            currentIndex = (currentIndex + 1) % totalSlides; // Avançar para o próximo índice
            slides[currentIndex].checked = true; // Marcar o próximo slide
        }

        setInterval(showNextSlide, 3000); // Mudar de slide a cada 3 segundos


        window.onload = function() {
            var form = document.getElementById('newletter');
            if (form) {
                var errorElements = form.querySelectorAll('.erro-menssage');
                var sucessElements = form.querySelectorAll('.sucess-menssage');
                if (errorElements.length > 0) {
                    form.scrollIntoView();
                }
                if (sucessElements.length > 0) {
                    form.scrollIntoView();
                }
            }
        };
    </script>   

</body>
</html>